apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: android-world-hpa
  namespace: android-world
  labels:
    app: android-world
    component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: android-world
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: android-world-service
  namespace: android-world
  labels:
    app: android-world
spec:
  selector:
    app: android-world
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: android-world
  namespace: android-world
  labels:
    app: android-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: android-world
  template:
    metadata:
      labels:
        app: android-world
    spec:
      containers:
      - name: android-world
        image: candidate/android-world:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: GENYMOTION_API_KEY
          valueFrom:
            secretKeyRef:
              name: genymotion-secret
              key: api-key
        - name: MAX_CONCURRENT_EPISODES
          value: "5"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
